apollo:
  appId: "silkyapp-gateway-host"
  cluster: default
  metaServer: "http://127.0.0.1:8080/"
  namespaces:
    - application
    - TEST1.silky.sample
    - TEST1.silky.sample.gateway
  env: DEV
  meta:
    DEV: "http://127.0.0.1:8080/"
    PRO: "http://127.0.0.1:8080/"
    