rpc:
  host: 0.0.0.0
  token: rpcTokenValue
registrycenter:
  connectionStrings: registrycenterconnections
  registryCenterType: registrycentertype
distributedCache:
  redis:
    isEnabled: true
    configuration: redisconfiguration
gateway:
  wrapResult: true
  jwtSecret: gatewayjwtsecret