rpc:
  host: 0.0.0.0
  token: rpcTokenValue
governance:
  timeoutMillSeconds: 0  
registrycenter:
  connectionStrings: registrycenterconnections
  registryCenterType: registrycentertype
distributedCache:
  redis:
    isEnabled: redisenable
    configuration: redisconfiguration
gateway:
  jwtSecret: gatewayjwtsecret
swaggerDocument:
  organizationMode: Group
  injectMiniProfiler: true
  termsOfService: https://www.github.com/liuhll/silky