rpc:
  token: ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW
governance:
  executionTimeout: -1
registrycenter:
  connectionStrings: silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181
  registryCenterType: Zookeeper
distributedCache:
  redis:
    isEnabled: true
    configuration: silky.redis1:6379,defaultDatabase=0
lock:
  lockRedisConnection: silky.redis1:6379,defaultDatabase=1
connectionStrings:
    default: server=silky.mysql;port=3306;database=account;uid=root;pwd=qwe!P4ss;
cap:
  rabbitmq:
    hostName: silky.rabbitmq
    userName: rabbitmq
    password: rabbitmq
jwtSettings:
  secret: UnMTH4QvAAp0BLYyEmdXYjoAOv4biHW4
skyWalking:
  transport:  
    gRPC:
      servers: "oap:11800"