rpc:
  host: 0.0.0.0
  port: rpcPortValue
  token: rpcTokenValue
governance:
  executionTimeout: -1
registrycenter:
  connectionStrings: registrycenterconnections
  registryCenterType: registrycentertype
distributedCache:
  redis:
    isEnabled: true
    configuration: redisconfiguration
connectionStrings:
  default: server=127.0.0.1;port=3306;database=SilkyApp;uid=root;pwd=qwe!P4ss;