version: "3.7"

services:
  lms.redis1:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - lms_service_net
networks:
  lms_service_net:
    external:
      name: lms_service_net
