rpc:
  token: ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW
governance:
  executionTimeout: -1
registrycenter:
  connectionStrings: silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181
  registryCenterType: Zookeeper
distributedCache:
  redis:
    isEnabled: true
    configuration: silky.redis1:6379,defaultDatabase=0
lock:
  lockRedisConnection: silky.redis1:6379,defaultDatabase=1
connectionStrings:
    default: server=silky.mysql;port=3306;database=stock;uid=root;pwd=qwe!P4ss;  