version: '3.7'

services:
  silky.sample.account:
    image: silkyframework/sample.account:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/account/Silky.AccountHost/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-ContainerDev}
    networks: 
      - silky_service_net
    
  silky.sample.order:
    image: silkyframework/sample.order:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/order/Silky.OrderHost/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-ContainerDev}
    networks: 
      - silky_service_net
  
  silky.sample.stock:
    image: silkyframework/sample.stock:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/stock/Silky.StockHost/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-ContainerDev}
    networks: 
      - silky_service_net

  silky.sample.gateway:
    image: silkyframework/sample.gateway:${TAG:-latest}
    build:
      context: ../..
      dockerfile: aggregators/Silky.GatewayHost/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-ContainerDev}
      ASPNETCORE_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-ContainerDev}
    ports:
      - 80:80
    networks: 
      - silky_service_net

networks:
  silky_service_net: 
    external:
      name: silky_service_net