version: '3.7'

services:
  silkyapp.gateway:
    image: silkyappgateway:${TAG:-latest}
    build:
      context: ../..
      dockerfile: gateways/SilkyApp.GatewayHost/Dockerfile
    volumes:
      - ./logs/gateway:/app/logs      
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      ASPNETCORE_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
    ports:
      - 80:80
    networks: 
      - silky_service_net

networks:
  silky_service_net: 
    external:
      name: silky_service_net